version: '3.8'

services:
  nextjs-app:
    build:
      context: ../
      dockerfile: Docker Configurations/nextjs_Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
