export const metadata = {
  title: 'Next.js', 
  description: 'Generated by Next.js', // Define your default page description here
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const activationToken = process.env.NEXT_PUBLIC_IDX_ACTIVATION_TOKEN; // Fetch the activation token from environment variables

  return (
    <html lang="en">
      <head>
        {/* Include the IDX script and configuration */}
        <script src="https://kestrel.idxhome.com/ihf-kestrel.js"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.ihfKestrel = window.ihfKestrel || {};
              ihfKestrel.config = {
                platform: "",
                activationToken: "${activationToken}", // Use the activation token from the environment variable
              };
            `,
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
