name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  # Builds the project and notifies the team of the outcome
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'

    # Setup & Building Section
    - name: Install dependencies
      run: npm install
      working-directory: my-app 

    - name: Run tests         # Currently No tests yet 
      run: npm test
      working-directory: my-app

    - name: Build project
      run: npm run build 
      working-directory: my-app

    # Push Results to Discord
    - name: Send notification to Discord
      uses: rjstone/discord-webhook-notify@v1.0.0
      if: always()  # This ensures the notification is sent whether the previous steps failed or succeeded
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
        username: 'GitHub Actions CI'
        text: >
          **CI Update**:
          - **Repository**: ${{ github.repository }}
          - **Run**: [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Status**: ${{ job.status }}
          - **Branch**: ${{ github.ref_name }}
          - **Commit**: ${{ github.sha }}
          - **Actor**: ${{ github.actor }}
          - **Event Name**: ${{ github.event_name }}

 