name: Commit Message Check

on: [push]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Validate commit messages
        run: |
          echo "Checking commit messages..."
          pattern='^#[A-Z][A-Z]-[0-9][0-9]+$'
          error_flag=0
          for commit_message in $(git log --format=%s ${{ github.event.before }}..${{ github.event.after }}); do
              echo "Commit message: $commit_message"
              if ! [[ "$commit_message" =~ $pattern ]]; then
                  echo "Error: Invalid commit message: \"$commit_message\""
                  echo "Commit messages must match the pattern '#[A-Z][A-Z]-[0-9][0-9]+', e.g., #AA-101."
                  error_flag=1
              fi
          done
          if [ "$error_flag" -ne 0 ]; then
              exit 1
          fi
